export const EixosTematicos: Record<string, string[]> = {
    "Meio Ambiente": [
        "Desmatamento",
        "Queimadas",
        "Crise hídrica",
        "Poluição marinha",
        "Preservação ambiental",
        "Agricultura sustentável",
        "Urbanização",
        "Ecoturismo",
    ],
    "Questões Sociais": [
        "Racismo",
        "Violência",
        "População de rua",
        "Trabalho infantil",
        "Abandono",
        "Moradia periférica",
        "Acesso à cultura",
    ],
    "Saúde e Ciência": [
        "Saúde mental",
        "Negacionismo",
        "SUS",
        "Gravidez na adolescência",
        "Pandemias",
        "Drogas",
        "Ética científica",
    ],
    "Direitos e Cidadania": [
        "Direito ao voto",
        "Criminalização da pobreza",
        "Minorias",
        "Intolerância religiosa",
        "Discurso de ódio",
        "PCD",
        "Igualdade de gênero",
    ],
    "Educação": [
        "Inclusão escolar",
        "Desigualdade na educação",
        "Alfabetização infantil",
        "Cotas",
        "Valorização do professor",
        "Ensino técnico",
    ],
    "Tecnologia": [
        "Cibersegurança",
        "IA",
        "Privacidade na internet",
        "Dependência tecnológica",
        "Inclusão digital",
        "Streaming",
        "Fake news",
        "Deep Fake",
    ],
    "Economia": [
        "Empreendedorismo",
        "Desemprego",
        "Economia criativa",
        "Desigualdade econômica",
        "Distribuição de renda",
        "Trabalho informal",
        "Inflação",
        "Justiça fiscal",
        "investimentos",
    ],
    "Arte e Cultura": [
        "Cultura periférica",
        "Valorização da arte",
        "Línguas indígenas",
        "Liberdade artística",
        "Arte na educação",
        "Festivais culturais",
        "Arte nas redes",
    ],
};

export const EixoOptions = Object.keys(EixosTematicos);